---
apiVersion: v1
kind: Service
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "ui.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
#    nodePort: 32092
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
