version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - reddit_db:/data/db
    networks:
      default:
        aliases:
          - post_db
          - comment_db
          - mongo_db
  ui:
    image: ${USER_NAME}/ui:${UI_V}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    image: ${USER_NAME}/post:${POST_V}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    image: ${USER_NAME}/comment:${COMMENT_V}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  reddit_db:
  prometheus_data:
  
networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/2      
