#FROM python:3.6.0-alpine
FROM python:3.6-alpine

WORKDIR /app
ADD . /app

RUN apk --no-cache --update add build-base && \
pip install -r /app/requirements.txt && \
apk del build-base && \
pip show markupsafe

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
#CMD tail -f
