---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: reddit
    component: mongo
    comment-db: "true"
    post-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        comment-db: "true"
        post-db: "true"
    spec:
      containers:
        - image: mongo:4
          name: mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          # name: mongo-gce-pd-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

#        volumeMounts:
#         - name: mongo-data
#           mountPath: /data/db
#      volumes:
#      - name: mongo-data
#        emptyDir: {}

#name: mongo-persistent-storage

##      hostAliases:
##      - hostnames:
##        - "postdb"
##        - "commentdb"
##        - "mongodb"
##        ip: "10.244.69.200"
#TEST:
#      volumes:
#      - name: mongo-data
#        hostPath:
#          path: "/data/db"
#
#ODLS
#        volumes:
#          - reddit_db:/data/db
#        networks:
#          default:
#            aliases:
#              - post_db
#              - comment_db
#              - mongo_db
