#image: alpine:latest

stages:
  - test
  - staging
  - production

test:
  stage: test
  script:
    - exit 0
  only:
    - triggers
    - branches

staging:
  stage: staging
  variables:
    KUBE_NAMESPACE: staging
    host: staging
    CI_REGISTRY: "index.docker.io"
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY/$CI_PROJECT_PATH
    CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
    CI_CONTAINER_NAME: ci_job_build_${CI_JOB_ID}
    GITLAB_NAME_HOST: gitlab.example.ap.e4u.ru
#
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  image: alpine/helm:3.2.1
  environment:
    name: staging
    url: http://staging
  only:
    refs:
      - master
#    kubernetes: active
  script:
#   install_dependencies
    - apk add git curl
    - helm version --client
#   ensure_namespace
# 	manual
#   deploy
    - ls -al
    - echo $KUBE_NAMESPACE
    - export track="${1-stable}"
    - name="$CI_ENVIRONMENT_SLUG"
#    - echo "Clone deploy repository..."
#    - git clone http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/reddit-deploy.git
#    - echo "Download helm dependencies..."
#    - helm dep update reddit-deploy/reddit
    - helm dep build reddit
#?    # for microservice in $(helm dep ls | grep "file://" | awk '{print $1}') ; do
#?    #   SET_VERSION="$SET_VERSION \ --set $microservice.image.tag='$(curl http://gitlab-gitlab/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)' "
    - echo "helm upgrade --install --wait --set ui.ingress.host="$host" --set ui.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)" --set post.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/post/raw/master/VERSION)" --set comment.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/comment/raw/master/VERSION)" --namespace="$KUBE_NAMESPACE" --version="$CI_PIPELINE_ID"-"$CI_JOB_ID" "$name" ./reddit"
    - >
      helm upgrade --install \
        --wait \
        --set ui.ingress.host="$host" \
        --set ui.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)" \
        --set post.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/post/raw/master/VERSION)" \
        --set comment.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/comment/raw/master/VERSION)" \
        --namespace="$KUBE_NAMESPACE" \
        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
        "$name" \
        ./reddit
    - echo "the end"

production:
  stage: production
  variables:
    KUBE_NAMESPACE: production
    host: production
    CI_REGISTRY: "index.docker.io"
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY/$CI_PROJECT_PATH
    CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
    CI_CONTAINER_NAME: ci_job_build_${CI_JOB_ID}
    GITLAB_NAME_HOST: gitlab.example.ap.e4u.ru
#
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  image: alpine/helm:3.2.1
  environment:
    name: production
    url: http://production
  when: manual
  only:
    refs:
      - master
#    kubernetes: active
  script:
#   install_dependencies
    - apk add git curl
    - helm version --client
#   ensure_namespace
#	 manual
#    deploy
    - echo $KUBE_NAMESPACE
    - export track="${1-stable}"
    - name="$CI_ENVIRONMENT_SLUG"
#    - echo "Clone deploy repository..."
#    - git clone http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/reddit-deploy.git
#    - echo "Download helm dependencies..."
#    - helm dep update reddit-deploy/reddit
    - helm dep build reddit
#?    # for microservice in $(helm dep ls | grep "file://" | awk '{print $1}') ; do
#?    #   SET_VERSION="$SET_VERSION \ --set $microservice.image.tag='$(curl http://gitlab-gitlab/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)' "
    - echo "helm upgrade --install --wait --set ui.ingress.host="$host" --set ui.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)" --set post.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/post/raw/master/VERSION)" --set comment.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/comment/raw/master/VERSION)" --namespace="$KUBE_NAMESPACE" --version="$CI_PIPELINE_ID"-"$CI_JOB_ID" "$name" ./reddit"
    - >
      helm upgrade --install \
        --wait \
        --set ui.ingress.host="$host" \
        --set ui.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/ui/raw/master/VERSION)" \
        --set post.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/post/raw/master/VERSION)" \
        --set comment.image.tag="$(curl -L http://$GITLAB_NAME_HOST/$CI_PROJECT_NAMESPACE/comment/raw/master/VERSION)" \
        --namespace="$KUBE_NAMESPACE" \
        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
        "$name" \
        ./reddit
    - echo "the end"
