version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:logging
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      front_net:
        aliases:
          - ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    build: ./post-py
    image: ${USERNAME}/post:logging
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
    logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
          tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    build: ./comment
    image: ${USERNAME}/comment:logging
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
