version: '3.3'
services:

  mongo_db:
    image: mongo:${DB_TAG}
    volumes:
      - post_db:${DB_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      - back_net
      - front_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
